---
- name: Установка Docker
  include_tasks: install.yml

- name: Настройка Docker daemon
  include_tasks: daemon.yml

- name: Настройка Docker Compose
  include_tasks: compose.yml

- name: Создание директорий для данных
  include_tasks: directories.yml

- name: Настройка systemd для Docker
  include_tasks: systemd.yml
