---
- name: Создание скрипта мониторинга приложения
  template:
    src: templates/app_monitor.sh.j2
    dest: /usr/local/bin/tg-rss-monitor.sh
    mode: '0755'

- name: Создание systemd таймера для мониторинга
  template:
    src: templates/app-monitor.service.j2
    dest: /etc/systemd/system/app-monitor.service
    mode: '0644'

- name: Создание systemd таймера
  template:
    src: templates/app-monitor.timer.j2
    dest: /etc/systemd/system/app-monitor.timer
    mode: '0644'

- name: Включение таймера мониторинга
  systemd:
    name: app-monitor.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Создание скрипта для резервного копирования
  template:
    src: templates/backup.sh.j2
    dest: /usr/local/bin/tg-rss-backup.sh
    mode: '0755'

- name: Создание systemd таймера для бэкапов
  template:
    src: templates/backup.service.j2
    dest: /etc/systemd/system/tg-rss-backup.service
    mode: '0644'

- name: Создание systemd таймера для бэкапов
  template:
    src: templates/backup.timer.j2
    dest: /etc/systemd/system/tg-rss-backup.timer
    mode: '0644'

- name: Включение таймера бэкапов
  systemd:
    name: tg-rss-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes
