---
- name: Создание директории для приложения
  file:
    path: /opt/tg-rss
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Создание директории для Docker volumes
  file:
    path: /opt/tg-rss/volumes
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Создание директории для бэкапов
  file:
    path: /opt/tg-rss/backups
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Создание директории для логов
  file:
    path: /opt/tg-rss/logs
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
