---
- name: Включение автоматических обновлений безопасности
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  when: ansible_os_family == "Debian"

- name: Настройка конфигурации автоматических обновлений
  template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
  when: ansible_os_family == "Debian"
