---
- name: Скачивание Alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz

- name: Распаковка Alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Копирование бинарного файла Alertmanager
  copy:
    src: "/tmp/alertmanager-0.27.0.linux-amd64/alertmanager"
    dest: /usr/local/bin/alertmanager
    mode: '0755'
    owner: prometheus
    group: prometheus
    remote_src: yes

- name: Копирование amtool
  copy:
    src: "/tmp/alertmanager-0.27.0.linux-amd64/amtool"
    dest: /usr/local/bin/amtool
    mode: '0755'
    owner: prometheus
    group: prometheus
    remote_src: yes

- name: Создание директории для Alertmanager
  file:
    path: /etc/alertmanager
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Создание systemd службы для Alertmanager
  template:
    src: templates/alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'

- name: Включение и запуск Alertmanager
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: yes

- name: Очистка временных файлов
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/alertmanager.tar.gz
    - /tmp/alertmanager-0.27.0.linux-amd64
