---
- name: Включение и запуск fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Настройка jail.local для SSH
  template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban
