---
- name: Перезагрузка systemd daemon
  systemd:
    daemon_reload: yes

- name: Создание директории для systemd override
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
